### ISSUE TITLE
Allow specify a alternative base domain

### ISSUE THREAD

**Issue by jeliasson** [jakeFeldman/strapi-provider-upload-azure-storage#1]
Hi,

First, thanks for the plugin @jakeFeldman!

I noticed that there is not a way to specify a alternative base url for files being uploaded, e.g. `https://static.domain.tld/uploads/[...]` rather than `https://<storageaccount>.blob.core.windows.net/uploads/[...]`. When checking the source code, it looks like it would be quite easy to extend another field with that information. However, this will cause problems for the `delete` operation towards the storage accounts.

Any thoughts on how to address an alternative domain to files being uploaded? I did not see anything related to this in the Strapi documentation. 

Speaking of delete operations. I noticed that the file being uploaded are not then visible in the Files Upload-page after a reload. I.e. upload a file, and it's shown in the view and in the storage account. A refresh of the page, and the files are gone from the view but are still in the database and on the storage account. What's going on here?

Thanks!

**Comment by jakeFeldman** [comment]
Hello @jeliasson,

Thanks for reaching out. What version of Strapi are you currently using?

1. I have not thought about adding an alternate domain. I would need to research a bit before being able to provide any incite. I'll look into adding an override and let you know if this is possible.

2. In regards to the issue in the admin panel, it appears that we are getting a `500` when Strapi fetches the images. I've classified this as a bug and will try to get it resolved this week.

**Comment by jeliasson** [comment]
Brilliant stuff good sir. I’ll have a look a bit later this day and get back to you.

**Comment by jeliasson** [comment]
@jakeFeldman Brilliant stuff good sir! I run version `v3.0.0-beta.18.7` of Strapi.
Let me know if you need any input or help with testing.

**Comment by jakeFeldman** [comment]
@jeliasson sorry for the delay here. I have been swapped at the normal 9 - 5 and haven't had time to work on this. I'd welcome a PR if you are actively trying to action this. I'm hoping next week I'll have some down time to at least fix the current bug.

**Comment by jeliasson** [comment]
@jakeFeldman Don't worry. I've been busy trying to get Strapi to run under a nice CI pipe with GitHub Actions and I'm almost there. After that I might have a look, and throw a PR your way :)

**Comment by jeliasson** [comment]
@jakeFeldman I'm giving up on Strapi in it's current state. I tried to make peace with it, but I'm facing too many small issues around database relations (`globalId`-threads...). If at some point it becomes stable, I will give it another shot. But for now, feel free to close the issue if you'd like.

Have a great day!

**Comment by jakeFeldman** [comment]
@jeliasson Sorry to hear that. Good luck in future ventures. I'm going to close this issue. Best wishes.
