### ISSUE TITLE
Blob URL gets distorted with each Strapi upload error in Strapi 3.0.5

### ISSUE THREAD

**Issue by Istanful** [jakeFeldman/strapi-provider-upload-azure-storage#14]
In our application we have configured our `defaultPath` to `/` with the notion that it would default to the root path of the blob. Instead it created a folder with no name. This worked fine until we upgraded Strapi to 3.0.5. In that version this behaviour would spawn:

1. Upload a file. It is uploaded to i.e `//file.txt`
2. Delete that file from the media library. An error is thrown.
3. Upload the same file. It is now uploaded to `///file.txt`

I suspect the error comes from modifying the initial provider settings twice, but I have not looked into it any further. We will correct our configuration to fix our error, but i thought you might want to know. :)

**Comment by jakeFeldman** [comment]
Hello @Istanful, thanks for reaching out. I will look into this. Once confirmed I'll update or document better to prevent further issues.

**Comment by Istanful** [comment]
@jakeFeldman I just now noticed this can happen with other `defaultPath` configuration as well. Currently our `defaultPath` is configured to be `cms-assets`. 

The following steps are performed.

1. Upload a file. It is now uploaded to `cms-assets/file.txt`.
2. Replace that file in the media library. It is now uploaded to `cms-assets/cms-assets/file.txt`

**Comment by Istanful** [comment]
The problem was the reference to `containerUrl` in the delete function. It was fixed in fc93a64abee55abb1641b8d2a12cf772548bbe72. Updating the lib fixed it for us, when `defaultPath` is `cms-assets`. You might be able to close this issue.

**Comment by jakeFeldman** [comment]
@Istanful Thanks you for the update. Sorry I was slow to addressing this. I recently started a new job and the birth of my child happened. I'm going to close for now and glad to hear its working for you!

**Comment by Istanful** [comment]
@jakeFeldman No worries! Congratulations on your new child. :)
