### ISSUE TITLE
Dependencies missing from package.json

### ISSUE THREAD

**Issue by jsakas** [jakeFeldman/strapi-provider-upload-azure-storage#16]
In the documentation we have some dependencies:

```
Prerequisites
- Node 10+
- npm 6+
- strapi@3.0.0-beta.16+
```

You should be able to put these in the package.json to actually enforce them, so if someone tries to install this package and does not meet the requirements npm will give a warning, potentially reducing developer anxiety and debug time. 

For node/npm, use engines: https://docs.npmjs.com/files/package.json#engines
For strapi, use peerDependencies: https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by jakeFeldman** [comment]
Thanks for pointing that out. I'll add them to the pkg.json in the next release!
