### ISSUE TITLE
The provider package isn't installed

### ISSUE THREAD

**Issue by abachuk** [jakeFeldman/strapi-provider-upload-azure-storage#19]
"strapi": "3.2.4",
"strapi-provider-upload-azure-storage": "^1.1.1"
node v12.16.2
npm v 6.14.4

Even though the package is installed I still am getting the following error:
```
[2020-10-20T03:31:41.207Z] error Bootstrap function in plugin "upload" failed
[2020-10-20T03:31:41.208Z] error Error: The provider package isn't installed. Please run `npm install strapi-provider-upload-azure-storage`
```

Was there a change in strapi config requirements?

**Comment by jakeFeldman** [comment]
Hey @abachuk, thanks for reaching out. I haven't tested this in Strapi 3.2.4. Let me give it a try and see if I can replicate.

**Comment by jakeFeldman** [comment]
Hey @abachuk I have tested and everything is working as expected. Did you setup your `config/plugins.js` file?

**Comment by abachuk** [comment]
Yes, I tried putting plugins.js in `/config` and `/config/env/development`. Same error. I'll keep debugging. Thank you.

**Comment by jakeFeldman** [comment]
Will you send me your pkg json?

**Comment by abachuk** [comment]
```
{
  "name": "project-cms",
  "private": true,
  "version": "0.1.0",
  "description": "CMS",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "mysql": "^2.18.1",
    "sqlite3": "latest",
    "strapi": "3.2.4",
    "strapi-admin": "3.2.4",
    "strapi-connector-bookshelf": "3.2.4",
    "strapi-plugin-content-manager": "3.2.4",
    "strapi-plugin-content-type-builder": "3.2.4",
    "strapi-plugin-email": "3.2.4",
    "strapi-plugin-graphql": "3.2.4",
    "strapi-plugin-upload": "3.2.4",
    "strapi-plugin-users-permissions": "3.2.4",
    "strapi-provider-upload-azure-storage": "^1.1.1",
    "strapi-utils": "3.2.4"
  },
  "author": {
    "name": ""
  },
  "strapi": {
    "uuid": "xxx"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**Comment by jakeFeldman** [comment]
Everything looks good there. Naive question, have you blown away your `./node_modules` and re-installed?

**Comment by abachuk** [comment]
yes, tried that. I'll report back when I figure it out. Thanks!

**Comment by jakeFeldman** [comment]
Sounds good. Let me know how I can help! Good luck!

**Comment by jakeFeldman** [comment]
@abachuk were you able to resolve your issues?

**Comment by abachuk** [comment]
couldn't figure it out unfortunatelly. If no one else has this issue, we can close it.

**Comment by ksaitor** [comment]
same issue heere

**Comment by jakeFeldman** [comment]
@ksaitor Glad you were able to resolve this. 

@abachuk I'm going to close this issue due to inactivity.
