### ISSUE TITLE
No preview images of uploaded files

### ISSUE THREAD

**Issue by dsfrederic** [jakeFeldman/strapi-provider-upload-azure-storage#20]
![image](https://user-images.githubusercontent.com/28486949/98469801-0e3aeb80-21e2-11eb-9157-33426a0367fd.png)
 
I've uploades some assets with this provider. I can see they're created in the storage account but they're not showing in Strapi... Can you help me with this please?

**Comment by jakeFeldman** [comment]
Hey thanks for reaching out. What version of Strapi are you using? What version of the plugin are you using?

**Comment by dsfrederic** [comment]
Hey @jakeFeldman 

```
    "strapi": "3.1.7",
    "strapi-admin": "3.1.7",
    "strapi-connector-bookshelf": "3.1.7",
    "strapi-plugin-content-manager": "3.1.7",
    "strapi-plugin-content-type-builder": "3.1.7",
    "strapi-plugin-email": "3.1.7",
    "strapi-plugin-upload": "3.1.7",
    "strapi-plugin-users-permissions": "3.1.7",
    "strapi-provider-upload-azure-storage": "^1.1.1",
```

**Comment by dsfrederic** [comment]
I allowed public access to the strapi container.

Is this a requirement? Isn't possible to authenticate via strapi?

**Comment by jakeFeldman** [comment]
Great question. I believe the storage objects need public access since its still a third party service that is accessing the storage objects. I would need to do some research to validate.

**Comment by avdeyev** [comment]
The same situation. Security team in our company wants to use only private access to storage. I'm trying to find quick solution. We could create a plugin to authenticate as microsoft user, and customise media library/markdown editor to handle additional headers. But it is too much, probably. Any ideas so far?

**Comment by jakeFeldman** [comment]
Hey @avdeyev, Definitely a valid use case. Do you know if Strapi has any issues with the AWS provider? I have not had time to look into this. I'm curious if there is a solved solution with another provider.

**Comment by mdekrey** [comment]
Something like https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview could be implemented for the public links, since the account keys are available. Would you be open to a PR for this? This would allow the container to remain private.

**Comment by jakeFeldman** [comment]
@mdekrey Thanks for looking into this. I'd be open to a PR for these changes!

**Comment by jakeFeldman** [comment]
Going to close this since it doesn't affect public images. If someone would like to add the feature I would happily accept a PR.
