### ISSUE TITLE
How to upload/preview images with SAS Token?

### ISSUE THREAD

**Issue by helderburato** [jakeFeldman/strapi-provider-upload-azure-storage#22]
## Description

Is there any way to upload images using `SAS Token` instead of `accountKey`? 

-----

Related issues: #2

**Comment by helderburato** [comment]
Just to give a heads up, it wasn't possible to use SAS Token, and because of this we moved to another approach to upload.

**Comment by jakeFeldman** [comment]
Hey. Sorry for the delayed response. Too bad that it doesnt support SAS Tokens. Best of luck!
