### ISSUE TITLE
conditional loading based on environment 

### ISSUE THREAD

**Issue by mkreder** [jakeFeldman/strapi-provider-upload-azure-storage#24]
Hi,

Is there any way to load this plugin only if Strapi is running in production mode?

In a client environment we are working we are using Azure App Service in the production environment.  All Azure Blob information is provided through the environment variables to the container. However, when we run in development mode locally, we would rather not load this plugin as we don't want to share credentials directly with the development team. If environment variables are not set, the plugin fails to load. I know we can temporarily remove or gitignore the plugins.js file but I was wondering if there is a better way. 

Thanks,
Matias

**Comment by jakeFeldman** [comment]
Hey Matias,

I haven't really tried to disable this plugin in dev. I think you can setup different providers per env. I have not tried this but it should work.

```
https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#configuration-per-environment
```

**Comment by mkreder** [comment]
@jakeFeldman I will try that, thanks!
