### ISSUE TITLE
No feature for use Azure Storage connection strings instead of Account Key?

### ISSUE THREAD

**Issue by cotcac** [jakeFeldman/strapi-provider-upload-azure-storage#26]
From Azure docs
"Your storage account access keys are similar to a root password for your storage account."
So how can we use Connection string instead?

**Comment by jakeFeldman** [comment]
Hey @cotcac at this time there is no support for connection strings. As shown in the docs (https://www.npmjs.com/package/@azure/storage-blob) the blob service client would need to be created using the fromConnectionString method. I'm open to a PR that supports connection strings as well as the SharedKeyCredential flow.

**Comment by jakeFeldman** [comment]
Closing due to lack of interest
