### ISSUE TITLE
Allow deleting file that is already deleted in Azure blob container

### ISSUE THREAD

**Issue by Moprheus** [jakeFeldman/strapi-provider-upload-azure-storage#27]
Hi, i'm having the same issue meantioned here - https://github.com/strapi/strapi/pull/8410
Once an image is deleted in azure (using azure UI), I cannot delete the same file in strapi admin.
Please do check, thank you

**Comment by jakeFeldman** [comment]
Hey @Moprheus, Sorry for the delayed response. 

Probably would need to add a check around [here](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/blob/master/lib/index.js#L93) to see if the blob exists. If not, resolve. My use case doesnt allow Azure access and users can only delete inside of strapi. Would happily accept a PR for this change.

**Comment by jakeFeldman** [comment]
Due to inactivity I'm going to close the issue. Thanks again for reaching out.
