### ISSUE TITLE
Tmp folder for files is not cleaned up after uploading files

### ISSUE THREAD

**Issue by leonelllagumbay** [jakeFeldman/strapi-provider-upload-azure-storage#29]
Hi

Uploaded files in OS tmp folder is not cleaned up. This piles up and causes my azure app service crashes. 
![image](https://user-images.githubusercontent.com/10430751/123364631-5d823080-d5a7-11eb-9b45-423af2f43d77.png)

Restarting the app would not be a good solution to this I think. Is there anyway to clean this up after file uploads?

**Comment by jakeFeldman** [comment]
Where do these tmp files live? On the node server thats running strapi?

**Comment by leonelllagumbay** [comment]
@jakeFeldman yes its in the os.tmpdir(). Thanks

**Comment by jakeFeldman** [comment]
This seems like it would be more of a strapi issue since this plugin doesn't directly modify the file system. 

There is not additional info but others have reported similar issues. https://forum.strapi.io/t/uploaded-files-are-stored-in-tmp-system-folder-ubuntu/2650
