### ISSUE TITLE
Use of $web container

### ISSUE THREAD

**Issue by hughobrien** [jakeFeldman/strapi-provider-upload-azure-storage#38]
Hello! Firstly thank you for sharing your plugin!

We are using azure's [$web hosting feature](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website), which means we upload to a special container. The contents of this container are then made available over public HTTP(S).

e.g. `https://${account}.blob.core.windows.net/$web/image.jpg` is accessible (after CNAMEing) as `https://mysite.com/image.jpg`. 

Setting `containerName` to `$web` places the media in the correct place, but the URL returned by strapi still contains the `$web` reference, resulting in ` https://mysite.com/%24web/image.jpg` being returned. This is invalid and results in a 404.

Perhaps '$web' can be stripped prior to returning?

**Comment by jakeFeldman** [comment]
Hello, sorry I missed this. I'd have to take a peek but I think this could be supported. Would you be willing to put up a PR? I'm pretty strapped for time currently. 

Thanks in advance and sorry for the delayed response.

**Comment by hughobrien** [comment]
Thank you! We have a workaround at the moment but I'll see if I can get a PR together. Appreciate your help.

**Comment by jakeFeldman** [comment]
Awesome! Glad you found a work around. If you can disclose that here incase anyone else runs into this issue that would be great as well. Thanks!

**Comment by hughobrien** [comment]
We used a cloudflare rewrite rule, which is easy but hackey. Only useful if you're already on CF but I'm sure there's a similar feature in nginx. Good luck.

**Comment by rvdkooy** [comment]
I see. we probably have to do something similar or copy the code and strip out the containername
thanks!
