### ISSUE TITLE
Setting fields value

### ISSUE THREAD

**Issue by juliensl** [jakeFeldman/strapi-provider-upload-azure-storage#4]
Hi !

I would like to use this provide to upload my images on my Azure blob container.
I installed the package, but I do not understand what should I write in this setting fields : 
`The path to use when there is none being specified`
`The maximum concurrent uploads to Azure`

It could be interesting to explain it in the README.md :) 

Thank you for your work ! :hugs:

**Comment by jakeFeldman** [comment]
Hello @juliensl,

Thanks for writing this. I have updated the README (https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/pull/6) to include descriptions for the required fields.

Hopefully this helps
