### ISSUE TITLE
Admin portal is unable to load all the images

### ISSUE THREAD

**Issue by gastuti-reply** [jakeFeldman/strapi-provider-upload-azure-storage#41]
Hi,
maybe I'm doing something wrong, I'm quite sure, actually 🤣 

I installed the plugin correctly and I'm able to upload media to the blob storage on azure.

What should I do to have the correct base-url of images and thumbnails while navigating the admin portal?

All my media are like this 
<img width="513" alt="Screenshot 2022-04-28 at 00 46 12" src="https://user-images.githubusercontent.com/91313526/165643567-d622b835-7830-4b88-8b19-14ea53edcaf2.png">

because the portal is trying to load the image from `http://localhost:1337/uploads/thumbnail_xxx` or `http://mywebsite/uploads/thumbnail_xxx`. 

Instead, Strapi should automatically understand that the images are in `http://myblobstorage/uploads/thumbnail_xxx`, right?

How can I achieve this?

Also, is there a way to have the APIs return the whole complete URL? I can imagine that for a frontend dev it could be tricky to change the base-url all the time.

Thank you for the support!

**Comment by gastuti-reply** [comment]
Fixed. 
I wasn't considering that the database tracks where from where the files are uploaded, all my images were uploaded with provider local since they have been migrated from a version without the azure storage provider.

**Comment by jakeFeldman** [comment]
Hello @gastuti-reply Thanks for the issue and glad you found a solution. Sorry for the delayed response. Im home and work life have been a bit more demanding these days. Best of luck!
