### ISSUE TITLE
An internal server error occurred

### ISSUE THREAD

**Issue by arielkarlen** [jakeFeldman/strapi-provider-upload-azure-storage#42]
strapi: 3.6.8,
Node: 16.9.1
Npm: 7.21.1

Hello!
I have installed the plugin, created the .env file and plugins.js in config/.

When trying to upload a file, I get the error "An internal server error occurred"

Surely I will be missing some other configuration, since the credentials are ok. 

I tried removing Node Modules and reinstalling. Also with a build --clean

Thanks!

**Comment by jakeFeldman** [comment]
Hello @arielkarlen, thanks for posting. Did you follow strapi 4.0+ or strapi 3.0+ install directions?

**4.0+** https://github.com/jakeFeldman/strapi-provider-upload-azure-storage#strapi-version--400
**3.0+** https://github.com/jakeFeldman/strapi-provider-upload-azure-storage#strapi-version--300---400

**Comment by arielkarlen** [comment]
@jakeFeldman 3.0+

![image](https://user-images.githubusercontent.com/28599365/166309302-2dc9a18f-ff7c-48c7-ad28-b7046ebbc0d2.png)

**Comment by phripley** [comment]
@arielkarlen in line 10 of plugins.js you don't want that final comma.

Also, you know that even tho strapi 4.x has been out for a while there is still a newer version of Strapi 3:

https://github.com/strapi/strapi/releases/tag/v3.6.9

There's a milestone for Strapi 3.6.10 as well, which pleased me when I saw that today.

**Comment by jakeFeldman** [comment]
Thanks for the reply @phripley! Going to close this issue for now!
