### ISSUE TITLE
Uploads are blocked by default cross security policy

### ISSUE THREAD

**Issue by davestevens** [jakeFeldman/strapi-provider-upload-azure-storage#44]
In the Strapi media view the uploaded files are blocked due to the default CSP.
Following the discussion here https://github.com/strapi/strapi/issues/11637#issuecomment-977244572 I was able to resolve using:

config/middlewares.js
```js
module.exports = ({ env }) => [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', env('STORAGE_URL')],
          'media-src': ["'self'", 'data:', 'blob:', env('STORAGE_URL')],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

You might want to add something to the README about adding this config?

**Comment by jakeFeldman** [comment]
Hello @davestevens! Thanks for the info. I'd be happy to accept a PR to update the README to include this info. Do you have the bandwidth to open a PR?
