### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by f-masche** [jakeFeldman/strapi-provider-upload-azure-storage#47]
Hello,
I want to be able to provide images in webp format. It would be convenient if uploaded images (jpg, png) get automatically converted and stored on the CDN as webp, in addition to the original format. 
There is already a similar plugin for AWS https://github.com/gfritzdev/strapi-provider-upload-aws-s3-with-webp
Would it be possible to add this functionallity to this plugin as well?

**Comment by phripley** [comment]
@f-masche how does that work in practice?  You have two files with exactly the same name but one is .png/.jpg and the other is .webp?

And then you do something like this: 

(assuming here that the application is consumed by a browser)

```
<picture>
  <source type="image/webp" srcset="https://cdn.example.com/image.webp">
  <img src="https://cdn.example.com/image.png">
</picture>
```

**Comment by f-masche** [comment]
I've implemented the webp and avif formats. Let me know what you think.

**Comment by phripley** [comment]
I don't think I'm qualified to review this code but if this feature works it will be really great for me!

**Comment by jakeFeldman** [comment]
Thanks for the PR. I'll take a look later today or early tomorrow!

**Comment by jakeFeldman** [comment]
Closing stale issue. Thanks!
