### ISSUE TITLE
Azure Blob Storage version deprecated.

### ISSUE THREAD

**Issue by kid-three** [jakeFeldman/strapi-provider-upload-azure-storage#52]
Hi,

Thanks for this package. Helped out a lot. JI just got it all working.

I get the following warning

`npm WARN deprecated @azure/storage-blob@10.5.0: This version has been deprecated, please upgrade to the version tagged as latest`

Seeing as @azure/storage-blob is nos on version 12.x, would it be prudent to update this dependency?

**Comment by jakeFeldman** [comment]
Hello @kid-three thanks for reaching out. I have looked into upgrading but there are breaking changes and have not had the time to implement the upgrade. I would welcome any PRs for this but at this time I'm not able to commit the time to the work. Thanks!

**Comment by spoilerdo** [comment]
What are the breaking changes? And how do I setup a test environment?

**Comment by jakeFeldman** [comment]
Hello @spoilerdo, @azure/storage-blob is deprecated and should be updated. As for the APIs that have changed I'm not 100%. I test locally with a local strapi and `yarn link`

**Comment by jakeFeldman** [comment]
Thanks for flagging I've updated the plugin and will be releasing a new version.

**Comment by jakeFeldman** [comment]
Addressed in https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/pull/57
