### ISSUE TITLE
Security middlewares config missing domain used for plugins images

### ISSUE THREAD

**Issue by martinsilha** [jakeFeldman/strapi-provider-upload-azure-storage#55]
The security policy provided doesn't include the domain that Strapi uses to host their images for the plugin library. Adding 'https://dl.airtable.com/ to 'img-src' worked for me and I can see all plugin images.

**Comment by jakeFeldman** [comment]
Hello @martinsilha, this plugin doesn't set any CSP headers. Maybe this is happening on the strapi side?

**Comment by martinsilha** [comment]
@jakeFeldman Sorry I wasn't very clear.  This is in reference to the "Security Middleware Configuration" portion of the README for this plugin.  If you copy and paste the CSP as is, you will not be able to see the plugin images in the marketplace. Unless I'm wrong in how Strapi operates, when we copy and paste this it will override the default `strapi::security` middlewares configuration so adding the domain to the provided config is necessary.

The images are coming from the `dl.airtable.com` domain so once I added that to the provided CSP config in the README, everything was fine.  You can see how the official Strapi maintained AWS-S3 provider addresses this: https://market.strapi.io/providers/@strapi-provider-upload-aws-s3

**Comment by jakeFeldman** [comment]
Thanks for providing this info. I'll update the read me to include this

**Comment by jakeFeldman** [comment]
addressed in https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/pull/57
