### ISSUE TITLE
Could not upload files into blob due to authorization

### ISSUE THREAD

**Issue by sixmund35** [jakeFeldman/strapi-provider-upload-azure-storage#56]
Hi,

I am using strapi-provider-upload-azure-storage with azurite. I did follow the readme. But I still can't get it worked. It always responds with error about authentication header (see attachment).
Could you please help on this?

I also ensure that Azurite works properly by browsing it via Storage Explorer. 

![upload_issue](https://user-images.githubusercontent.com/15127960/215978211-f405ea5d-aa8e-4fb9-ab6b-75d9cc8bfd09.png)

**Info:**  
OS: Ubuntu 22.04
Node version: 16.14.0
Strapi version: 4.3.2
strapi-provider-upload-azure-storage version: 2.1.0
azurite version: 3.21.0

**Log files:**
[debug.log](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/files/10554161/debug.log)

**plugin config**
```
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "strapi-provider-upload-azure-storage",
      providerOptions: {
        account: env("STORAGE_ACCOUNT"),
        accountKey: env("STORAGE_ACCOUNT_KEY"),
        serviceBaseURL: env("STORAGE_URL"),
        containerName: env("STORAGE_CONTAINER_NAME"),
        defaultPath: env("STORAGE_DEFAULT_PATH", "assets"),
        maxConcurrent: env("STORAGE_MAX_CONCURRENT", 10),
      },
    },
  },
});
```

**Middlewares**
```
name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", process.env.STORAGE_URL],
          "media-src": ["'self'", "data:", "blob:", process.env.STORAGE_URL],
          upgradeInsecureRequests: null,
        },
      },
    },
```

**env**
```
STORAGE_ACCOUNT=devstoreaccount1
STORAGE_ACCOUNT_KEY=*** # Start with Eby8vdM, end with GMGw==
STORAGE_URL=http://127.0.0.1:10000/devstoreaccount1
STORAGE_CDN_URL=not-using-cdn
STORAGE_CONTAINER_NAME=strapi
STORAGE_MAX_CONCURRENT=10
STORAGE_DEFAULT_PATH=assets
```
Thank you for the support!

**Comment by jakeFeldman** [comment]
Hello @sixmund35 thanks for reporting. Azurite support was added by someone else and I personally don't use it. Will you please give v3.0.0 a try and let me know if its still an issue?

**Comment by devendra-rgb** [comment]
> Hello @sixmund35 thanks for reporting. Azurite support was added by someone else and I personally don't use it. Will you please give v3.0.0 a try and let me know if its still an issue?

Hey @jakeFeldman  is there any feature to upload the data to blob using only SAS token because the access key will have access to all other containers in the storage account which will make security constriants but SAS will be enabled only for one container in azure

**Comment by jakeFeldman** [comment]
@devendra-rgb thanks for reaching out. I have considered adding other authentication methods. It's a little off topic for this issue. If you want to open a new issue, I can look into adding it this weekend.

**Comment by devendra-rgb** [comment]
Sure!

**Comment by sixmund35** [comment]
Hi @jakeFeldman, I tried with v3.0.0 and able to upload image without auth issue. Though I still face another issues. I can't view the image (See attached image). I haven't checked further if it is my local settings or not. But for now I can continue develop with Strapi with local storage easily now. Thanks!

![preview_image](https://user-images.githubusercontent.com/15127960/218352274-8cee7a65-f65b-4847-b4d4-b5353d29c5e6.png)

**Comment by jakeFeldman** [comment]
Hi @sixmund35, glad uploads are working now. Check to see if strapi is getting a 401, 403, or 404. Going to close this issue. If you can't resolve the new issue, please open a new issue and I'll look into it.
