### ISSUE TITLE
Could not upload files to blob using SAS token of a Container in Azure

### ISSUE THREAD

**Issue by devendra-rgb** [jakeFeldman/strapi-provider-upload-azure-storage#62]
Hi,

I am using strapi-provider-upload-azure-storage. I did follow the readme. But I got to know that SAS authentication is not there to upload files to the blob 

Thanks for the support!

**Comment by jakeFeldman** [comment]
Thanks for posting @devendra-rgb. I'll look into adding this weekend. I'll report back when I have a new version posted.

**Comment by devendra-rgb** [comment]
Hey, @jakeFeldman I managed to configure the package according to the requirement of the SAS token. I read the Microsoft documentation and found that we need to add a function  so can I work on this feature 

Thanks!

**Comment by jakeFeldman** [comment]
Yes, that would be great! Please assign yourself the issue and I welcome a PR

**Comment by devendra-rgb** [comment]
@jakeFeldman I created a PR please review it and tell me if there are any changes to be made.

**Comment by jakeFeldman** [comment]
Sorry for the delayed response. Testing the changes now!
