### ISSUE TITLE
Missing file extension

### ISSUE THREAD

**Issue by mario-mestrovic** [jakeFeldman/strapi-provider-upload-azure-storage#65]
Hi! 
Im using Strapi v4.6.1 (latest) and this plugin uploads fine but everything that gets uploaded to Azure Storage loses it's file extension.
Same happened on v4.6.0 and both with the latest plugin 3.1.2

I've tried on an older Strapi version v3.6.8 with plugin v2.1.0 and it works as expected there

**Comment by jakeFeldman** [comment]
Thanks for the issue and PR. I've merged your changes and will publish a new version here in a few. Thanks again!

**Comment by jakeFeldman** [comment]
Version 3.1.3 has been published. Thanks again!
