### ISSUE TITLE
Images failing to load in admin app

### ISSUE THREAD

**Issue by fbede4** [jakeFeldman/strapi-provider-upload-azure-storage#68]
Hi,

thanks for creating the provider.

I followed the README to set it up using a local azurite container, but after uploading the images, they fail to load in the admin app, with the following error:
![image](https://user-images.githubusercontent.com/29088644/226635387-8d1297e8-2b23-4708-b838-c6968bb1293d.png)
"Refused to load the image '...' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: dl.airtable.com http://localhost:10000/devstoreaccount1"

Is there something I'm doing wrong, or do you know the source of the issue?

Thanks in advance

**Comment by fbede4** [comment]
It turned out that in the middleware.js, the img-src has to be http://localhost:10000, without the account name, the documentation states the STORAGE_URL should work, which contains the account name, it didn't work that way for me.

**Comment by jakeFeldman** [comment]
Ahh this might Azurite specific. If you want to open a PR to update that docs I'd appreciate it! Thanks for reporting.
