### ISSUE TITLE
403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)

### ISSUE THREAD

**Issue by walterspieler** [jakeFeldman/strapi-provider-upload-azure-storage#75]
Hello, 
I hope you're all fine.

I have a bug when I try to download a media from the media library. My Azure config seems fine since I can upload media to my azure storage.

<img width="937" alt="Screenshot 2023-06-29 at 11 59 27" src="https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/13601781/5b2cd510-b870-4502-a391-f0f7da856596">

<img width="1014" alt="Screenshot 2023-06-29 at 11 37 39" src="https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/13601781/63ee7339-96e7-4286-82a3-ef92bb67aa88">

I can provide a screenshot of the query
<img width="1071" alt="Screenshot 2023-06-29 at 12 01 39" src="https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/13601781/aaef3884-816c-4168-896f-6c574186b695">

Thank you for your answers :)

**Comment by jakeFeldman** [comment]
Hello @walterspieler, thanks for reporting. I would need to do some testing to see how strapi is trying to download. Will you confirm that your access key has sufficient perms to allow downloads?

**Comment by jakeFeldman** [comment]
Sorry for the delay. I've been very busy at work ad have not had the time to work on this package. I'm looking for someone to help maintain the package.

**Comment by ArjanBlokJump** [comment]
The problem is that Strapi send the strapi bearer token to the storage url since the latest update.

**Comment by conradagramont** [comment]
In your associated .env file, you need to add the following:
STORAGE_ACCOUNT_SAS_TOKEN=

The problem in the code is this line:

if (sasToken != '') {

It's specifically looking for a blank value.  In my case, I didn't put that value into the .env and I'm assuming that it's determined to be a null value. Thus, the code within the if statement is always run.  

I did try putting in a value for "STORAGE_ACCOUNT_SAS_TOKEN" as well, but that didn't work either. Anyhow, it works now with the accountKey.

**Comment by jaredbouwer** [comment]
I'm having the same issue. When clicking download, wouldn't it be easier to just open the download link in a new tab?
