### ISSUE TITLE
Strapi cannot fetch images from azure blob storage container which is restricted to private access only

### ISSUE THREAD

**Issue by kemil-sakhareliya** [jakeFeldman/strapi-provider-upload-azure-storage#76]
If my container in storage account is restricted to private access only, strapi cannot fetch images back from blob.
And, I get 404 - Failed to load resource: the server responded with a status of 404 (The specified resource does not exist.)

It only fetch images if it is set to public.

Implementation below:

plugins.js:

module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "strapi-provider-upload-azure-storage",
      providerOptions: {
        account: env("STORAGE_ACCOUNT"),
        accountKey: env("STORAGE_ACCOUNT_KEY"),//either account key or sas token is enough to make authentication
        containerName: env("STORAGE_CONTAINER_NAME"),
        defaultPath: ".",
      },
    },
  },
});

What am I missing?

**Comment by jakeFeldman** [comment]
You'll need to update your permissions in azure.
