### ISSUE TITLE
Can not specify blobContentDisposition

### ISSUE THREAD

**Issue by CubanSoil** [jakeFeldman/strapi-provider-upload-azure-storage#77]
Hi, is possible to enable us to specify headers option before uploading to the blob storage ? 

e.g 

`const headers = {
    blobContentDisposition: "attachment" + (nameOverride && `; filename="${blob.path}"`)
  }
  await blockBlobClient.upload(blob, blob.size, { metadata: metadata, blobHTTPHeaders: headers, onProgress: onProgress })`

![image](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/40838330/aa5a4a5e-39c6-4efc-beb8-9b98ac4bca9e)

**Comment by jakeFeldman** [comment]
Currently this is not supported. This support is not on the roadmap
