### ISSUE TITLE
Supporting video uploads ?

### ISSUE THREAD

**Issue by bastien-germain** [jakeFeldman/strapi-provider-upload-azure-storage#78]
Hi, 

Does this provider support uploading videos ?
I'm guessing it's not (or at least it's not working for me !)

Does anyone know of a solution to upload videos to an azure storage container from Strapi ?

Thank you for your help !

**Comment by jakeFeldman** [comment]
Hello, I'm not sure if video upload is supported or not. I've never tested it. Please test and let me know if they're not supported

**Comment by jakeFeldman** [comment]
Going to close due to inactivity
