### ISSUE TITLE
Unable to download assets from Strapi Admin UI

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [jakeFeldman/strapi-provider-upload-azure-storage#86]
Hey,

I went through all instructions and it worked well for uploading assets and displaying their thumbnails. 

However, in Admin UI when I try to download asset, I see a CORS error. 
It seems like download is done client-side (unlike upload) and this requires CORS setup - unless your blob contains is under the same domain as Strapi itself.

So to fix this you need to set your Azure Blob storage account with CORS rule to allow such action. Example for terraform:
```terraform
resource "azurerm_storage_account" "strapi" {
  name                     = "strapi"   
  # ...
  blob_properties {    
        cors_rule {        
        allowed_headers = ["*"]
        allowed_methods = ["GET","HEAD"]
        allowed_origins = ["*"]
        exposed_headers = ["*"]
        max_age_in_seconds = 3600
        }
    }
}
```

Posting this issue for visibility if someone will be looking here for solution like myself.

**Comment by jakeFeldman** [comment]
Thanks for the post and solution. Hopefully this helps others in the future!
