### ISSUE TITLE
Upload assets into folders?

### ISSUE THREAD

**Issue by yanckst** [jakeFeldman/strapi-provider-upload-azure-storage#89]
Hi,

### Question
Is there a way to upload an asset into a specific folder instead of just putting all assets into the default folder or the folder used for the upload? 

-----
#### Strapi

For example, if in strapi I have a media galery like so : 

![image](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/30554401/0d72ede0-d863-49d2-b362-810752c1e6ae) 
![image](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/30554401/84fbac2d-4abb-482a-8bc1-17ee5b13414a)

-----
#### Azure

In azure, the structure looks like that

![image](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/assets/30554401/8f13e2e0-0850-4c8f-9e27-e57f478625ed)

----

#### Output

I was expecting the v2 file to be uploaded inside the folder inside the parent like it's already structured like that in strapi.

I want to know if this is a bug or missing feature.

Thanks and awesome work! :)

**Comment by jmather-aipm** [comment]
Folders in Strapi are part of the admin interface and not part of the upload plugin:  https://docs.strapi.io/dev-docs/plugins/upload#endpoints:~:text=Delete%20a%20file-,%E2%9C%8F%EF%B8%8F%20Note,-Folders%20are%20an

**Comment by yanckst** [comment]
Thanks for the information. We can close the issue.
