### ISSUE TITLE
issue Strapi Beta 20

### ISSUE THREAD

**Issue by Ayo91** [jakeFeldman/strapi-provider-upload-azure-storage#9]
I have been using this plugin in a prod env since some months and any issue. Works amazing!

However, we have a new version of Strapi where the configuration of the media plugins has to be using a json file. Im not able to configure the plugin to work with v20:

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html
https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider

**Comment by jakeFeldman** [comment]
Hello @Ayo91. Thanks for reaching out. Have you updated following the outline in the README (https://github.com/jakeFeldman/strapi-provider-upload-azure-storage#strapi-version--beta20x)? Please let me know if you try those changes and still run into issues.

**Comment by jakeFeldman** [comment]
@Ayo91 I'm going to close this due to inactivity. Please feel to re-open if you're still running into issues. Thanks.
